{
 "title": "Monitoramento",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fila Pagamento - Em processamento",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messaging_masstransit_consume_active_ea_total{messaging_masstransit_destination=\"payment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fila Pagamento - Processado",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "messaging_masstransit_consume_ea_total{messaging_masstransit_destination=\"payment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(process_memory_usage_bytes{})",
     "legendFormat": "${metric} (average)"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time_seconds_total{}[$__rate_interval]))",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Total de Novos Funcionários",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(Action) (custom_new_employees_counter_Employee_total{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Consultas - Funcionários",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "custom_get_employee_request_counter_Employee_total{job=\"otel-collector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "service": "employee-management-service" }
   ]
  },
  {
   "title": "Logs - Funcionários",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{service_name=\"employee-management-service\"} |= ``"
    }
   ]
  }
 ]
}