apiVersion: 1

providers:
  - name: Default # A uniquely identifiable name for the provider
    allowUiUpdates: true
    type: file
    options:
      path: /usr/lib/dashboards
        # Default path for Windows: C:/Program Files/GrafanaLabs/grafana/public/dashboards
        # Default path for Linux is: /var/lib/grafana/dashboards