version: '3.8'

services:
 # Jaeger
 jaeger:
   container_name: jaeger-tracing
   image: jaegertracing/all-in-one:latest
   ports:
     - "16686:16686"

 # Prometheus
 prometheus:
    container_name: prometheus-metrics
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

 # Collector
 collector:
   container_name: otel-collector
   image: otel/opentelemetry-collector
   volumes:
     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
   command: [ "--config=/etc/otel-collector-config.yaml" ]
   ports:
     - "4317:4317"   # OTLP gRPC receiver
     - "4318:4318"   # OTLP HTTP receiver
     - "8888:8888" # Prometheus metrics exposed by the collector
     - "8889:8889" # Prometheus exporter metrics
   depends_on:
     - jaeger
     - prometheus
  