version: '3.8'

services:

 # Jaeger
 jaeger:
   container_name: jaeger-tracing
   image: jaegertracing/all-in-one:latest
   ports:
     - "16686:16686"

 # Prometheus
 prometheus:
    container_name: prometheus-metrics
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

 # Grafana Loki
 loki:
    container_name: loki-logs
    image: grafana/loki:3.0.0
    volumes:
      - ./loki-config.yaml:/conf/loki-config.yaml
    command: [ "--config.file=/conf/loki-config.yaml" ]
    ports:
      - 3100:3100

 # Grafana
 grafana:
    container_name: grafana
    image: grafana/grafana:main-ubuntu
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./default.yaml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./dashboard.json:/usr/lib/dashboards/dashboard.json
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

 # Collector
 collector:
   container_name: otel-collector
   image: otel/opentelemetry-collector
   volumes:
     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
   command: [ "--config=/etc/otel-collector-config.yaml" ]
   ports:
     - "4317:4317"   # OTLP gRPC receiver
     - "4318:4318"   # OTLP HTTP receiver
     - "8888:8888" # Prometheus metrics exposed by the collector
     - "8889:8889" # Prometheus exporter metrics
   depends_on:
     - jaeger
     - prometheus
  