version: '3.8'

services:
 # Jaeger
 jaeger-all-in-one:
   container_name: jaeger-tracing
   image: jaegertracing/all-in-one:latest
   ports:
     - "16686:16686"
     - "14250"
 # Collector
 collector:
   container_name: otel-collector
   image: otel/opentelemetry-collector:0.29.0
   volumes:
     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
   command: [ "--config=/etc/otel-collector-config.yaml" ]
   ports:
     - "4317:4317"   # OTLP gRPC receiver
     - "4318:4318"   # OTLP HTTP receiver
   depends_on:
     - jaeger-all-in-one
  